customhost = "employees.ctahfleukivw.us-east-2.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employees"
custombucket = "sugumarbucket"
customregion = "us-east-2"
